---

name:
    hledger-stockquotes
version:
    0.1.0.0
github:
    prikhi/hledger-stockquotes
homepage:
    https://github.com/prikhi/hledger-stockquotes#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2020 Pavan Rikhi
category:
    Finance
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Short, one-line summary of project here.

description: |
    Longer description of package here.

    Maybe include a simple usage example.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        - aeson
        - bytestring
        - containers
        - hledger-lib
        - req
        - safe
        - scientific
        - split
        - text
        - time
        - unordered-containers

executables:
    hledger-stockquotes:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - hledger-stockquotes
            - bytestring
            - cmdargs
            - text

tests:
    hledger-stockquotes-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - hledger-stockquotes
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
